server:
  port: 7878
# 日志配置
logging:
  config: classpath:logback.xml
  level:
    root: info
  file:
    name: logfile.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"   # 可选：设置控制台日志输出格式
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
spring:
  datasource:
    url: jdbc:mysql://49.232.61.41:3306/tea_party?useSSL=false&serverTimezone=UTC
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 49.232.61.41
    port: 6379
#mybatis-plus:
#  configuration:
#    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

